### PR TITLE
Collabrate with us

### PR DESCRIPTION
**Pull request by Ham1993odee**
fixed ptoblems with buttons key prop and overlapping

### CODE REVIEW

**Comment by stefanpython** [comment]
the page looks good now on desktop and on mobile, good job. 

But there are still some errors to fix. Check the terminal or the development browser console
error1

error2


Also there are some merge conflicts that need to be addressed:
error3

**Comment by Ham1993odee** [comment]
Fixed the errors but about the conflict I don’t have permission to resolve
them

ons 11 dec. 2024 kl. 10:44 skrev stefanpython ***@***.***>:

**Comment by stefanpython** [comment]
Ask Kareem for permission

**Pull request closed without merging**
