### PR TITLE
Implement sign-up page

### PR DESCRIPTION
**Pull request by stefanpython**

### CODE REVIEW

**Comment by stefanpython** [comment]
Signup with google button is temporarily disabled, because there is not backend for it, and we`ve decided to move forward without  it for the moment

**Comment by xelleze** [comment]
when creating pr you need to merge to develop branch @dIB59 correct ?

**Comment by dIB59** [comment]
Yes

**Comment by xelleze** [comment]
@dIB59 another small questions since you told me to use shadcn have you told everyone else on the team to use it ?

**Comment by stefanpython** [comment]
is it ok if i haven`t used shadcn for the signup @dIB59 ? - it`s basically only a form.

**Comment by stefanpython** [comment]
@dIB59   is it ok if I haven`t used shadcn it in the signup ? - it`s basically just a form

**Review by xelleze — APPROVED** [review]

**Comment by dIB59** [comment]
@stefanpython as long as it works, we can always change it later

**Pull request merged**
