### PR TITLE
Account settings page created and styled

### PR DESCRIPTION
**Pull request by serenely**
### **Pull Request Title:**
Create `AccountSettings` Component with Functionalities and Styles

---

### **Description:**
This pull request introduces a new `AccountSettings` component, which provides a form interface for users to manage their account details. The component includes functionality for updating profile information, along with styling to ensure a clean and user-friendly design.

---

### **Features Added:**

1. **Component Creation:**
   - Created a new `AccountSettings` component using React and TypeScript.
   - Added functionality for rendering input fields dynamically based on a predefined configuration.

2. **Form Fields:**
   - Each field includes:
     - A label (e.g., "Full Name").
     - A placeholder for user input.
     - A description to guide the user.

3. **Dynamic Form Generation:**
   - Implemented a `FormField` subcomponent with props (`label`, `placeholder`, `descr`) to render form fields dynamically.

4. **Profile Photo Management:**
   - Added `Upload Photo` and `Remove Photo` buttons with styled designs for uploading and removing the profile image.
   - Used `next/image` to display the user's profile picture.

5. **Styling:**
   - Input fields styled with custom border width (`1.5px`) for better visibility.
   - Buttons styled with `rounded-md`, `italic`, and custom colors for a consistent UI.
   - Grid layout (`grid-cols-1` and `md:grid-cols-2`) for responsive alignment of form fields.

6. **Responsive Design:**
   - Ensured the component adapts to different screen sizes using Tailwind CSS utilities like `grid`, `gap-x`, and `md:grid-cols-2`.

7. **Positioning:**
   - Used absolute positioning for buttons and the profile image to ensure precise alignment within the layout.

---

### **Changes Made:**
- **`AccountSettings.tsx`**:
  - Defined the `AccountSettings` component.
  - Created the `FormField` subcomponent for dynamic input rendering.
  - Added hardcoded `formFields` array for managing field data.
  - Styled buttons and inputs for a clean, consistent look.
- **`profileImage.png`**:
  - Added a placeholder profile image for demonstration purposes.

---

### **Testing:**
- Verified all input fields render correctly with the provided configuration.
- Checked that buttons function as intended with proper styling.
- Ensured the layout is responsive on different screen sizes.

---

### CODE REVIEW

**Comment by stefanpython** [comment]
Account settings looks ok. I feel like you should also implement notifications and time zones before opening a PR, since they are all part of the Profile as a whole.

**Comment by stefanpython** [comment]
Also when creating a pull request, make sure to merge it in the "develop" branch, not main.

**Comment by serenely** [comment]
> Account settings looks ok. I feel like you should also implement notifications and time zones before opening a PR, since they are all part of the Profile as a whole. 

Yes, of course, I understand, just wanted to know that I made in the right way, or should I update or rewrite something.

**Comment by serenely** [comment]
> Also when creating a pull request, make sure to merge it in the "develop" branch, not main.

Oh, okay, sorry, should know

**Comment by stefanpython** [comment]
The account settings looks good :+1:

**Pull request closed without merging**
